#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
    systemctl enable epazote.service || true

    if [ -f /etc/epazote/epazote.yml ]; then
        systemctl restart epazote.service || true
    fi
fi

exit 0
